<?php
$cl_units = new units();
$cl_units->set_unitfactor("0.65","0.94355");

$cl_units->add_unit("Mızrakçı","unit_spear");
$cl_units->set_woodprice("50");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("10");
$cl_units->set_bhprice("1");
$cl_units->set_time("1000");
$cl_units->set_att("50","1.045");
$cl_units->set_def("100","1.045");
$cl_units->set_defcav("200","1.045");
$cl_units->set_defarcher("300","1.045");
$cl_units->set_speed("720");
$cl_units->set_booty("25");
$cl_units->set_needed(array());
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array("barracks"=>"1"));
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("def");
$cl_units->set_description("Bir şövalye hizmetkârı olmadan ne yapardı? Atlı birliklere karşı savunmada yararlı olan bu birlikler, az silaha sahip olsalar da kendilerini koruyabilir.");

$cl_units->add_unit("Kılıç Ustası","unit_sword");
$cl_units->set_woodprice("30");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("70");
$cl_units->set_bhprice("1");
$cl_units->set_time("1500");
$cl_units->set_att("100","1.045");
$cl_units->set_def("300","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("900");
$cl_units->set_booty("15");
$cl_units->set_needed(array("barracks"=>"1","smith"=>"1"));
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("def");
$cl_units->set_description("Kılıç ustaları sağlam kalkanlarıyla özellikle piyade saldırılarına karşı güçlü savunma birlikleridir.");

$cl_units->add_unit("Baltacı","unit_axe");
$cl_units->set_woodprice("60");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("40");
$cl_units->set_bhprice("1");
$cl_units->set_time("1250");
$cl_units->set_att("350","1.0455");
$cl_units->set_def("70","1.045");
$cl_units->set_defcav("50","1.045");
$cl_units->set_defarcher("50","1.045");
$cl_units->set_speed("720");
$cl_units->set_booty("10");
$cl_units->set_needed(array("barracks"=>"1","smith"=>"2"));
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("off");
$cl_units->set_description("Baltacılar savaş alanında savaş naraları atarak düşmanlarını korkutur ve baltalarıyla saldırır. Önleri açıldığında onları durdurmak zordur; bu yüzden en korkulan saldırı birliklerindendir.");

if($config['archers']){
	$cl_units->add_unit("Okçu","unit_archer");
	$cl_units->set_woodprice("100");
	$cl_units->set_stoneprice("30");
	$cl_units->set_ironprice("60");
	$cl_units->set_bhprice("1");
	$cl_units->set_time("1750");
	$cl_units->set_att("150","1.045");
	$cl_units->set_def("400","1.045");
	$cl_units->set_defcav("150","1.045");
	$cl_units->set_defarcher("100","1.045");
	$cl_units->set_speed("720");
	$cl_units->set_booty("10");
	$cl_units->set_needed(array("barracks"=>"5","smith"=>"5"));
	$cl_units->set_recruit_in("barracks");
	$cl_units->set_specials(array());
	$cl_units->set_group("archer");
	$cl_units->set_col("A");
	$cl_units->set_attType("def");
	$cl_units->set_description("Okçular keskin oklarıyla uzaktan savaşır; hem saldırı hem savunma ordularını destekleyebilir.");
}

$cl_units->add_unit("Casus","unit_spy");
$cl_units->set_woodprice("50");
$cl_units->set_stoneprice("50");
$cl_units->set_ironprice("20");
$cl_units->set_bhprice("2");
$cl_units->set_time("1250");
$cl_units->set_att("1","1.045");
$cl_units->set_def("10","1.045");
$cl_units->set_defcav("5","1.045");
$cl_units->set_defarcher("7","1.045");
$cl_units->set_speed("360");
$cl_units->set_booty("0");
$cl_units->set_needed(array("stable"=>1));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("spy");
$cl_units->set_description("Casusların gücü savaşmak değil, düşman köylerine gizlice girerek bilgi toplamaktır. Ne kadar çok casusunuz varsa raporlarınız o kadar ayrıntılı olur.");

$cl_units->add_unit("Hafif Süvari","unit_light");
$cl_units->set_woodprice("125");
$cl_units->set_stoneprice("100");
$cl_units->set_ironprice("250");
$cl_units->set_bhprice("4");
$cl_units->set_time("2400");
$cl_units->set_att("900","1.045");
$cl_units->set_def("200","1.045");
$cl_units->set_defcav("300","1.045");
$cl_units->set_defarcher("300","1.045");
$cl_units->set_speed("390");
$cl_units->set_booty("80");
$cl_units->set_needed(array("stable"=>3));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("off");
$cl_units->set_description("Hafif süvariler hızlı saldırı ve yağma görevlerinde kullanılan güçlü hareketli birliklerdir.");

if($config['archers']){
	$cl_units->add_unit("Atlı Okçu","unit_marcher");
	$cl_units->set_woodprice("250");
	$cl_units->set_stoneprice("100");
	$cl_units->set_ironprice("150 ");
	$cl_units->set_bhprice("5");
	$cl_units->set_time("1250");
	$cl_units->set_att("120","1.045");
	$cl_units->set_def("40","1.045");
	$cl_units->set_defcav("30","1.045");
	$cl_units->set_defarcher("50","1.045");
	$cl_units->set_speed("600");
	$cl_units->set_booty("50");
	$cl_units->set_needed(array("stable"=>"5" ));
	$cl_units->set_recruit_in("stable");
	$cl_units->set_specials(array(""));
	$cl_units->set_group("cav");
	$cl_units->set_col("B");
	$cl_units->set_description("Atlı okçular özellikle duvar arkasındaki düşman okçularına karşı etkilidir.");
}

$cl_units->add_unit("Ağır Süvari","unit_heavy");
$cl_units->set_woodprice("200");
$cl_units->set_stoneprice("150");
$cl_units->set_ironprice("600");
$cl_units->set_bhprice("6");
$cl_units->set_time("3600");
$cl_units->set_att("600","1.045");
$cl_units->set_def("1500","1.045");
$cl_units->set_defcav("1000","1.045");
$cl_units->set_defarcher("1000","1.045");
$cl_units->set_speed("450");
$cl_units->set_booty("50");
$cl_units->set_needed(array("stable"=>"10","smith"=>"15"));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("def");
$cl_units->set_description("Kara şövalyeleri uğursuz bir güçle çevrilidir. Onları görenlere korku salarlar ve hiçbir zayıflıkları yoktur; ancak işe almak son derece pahalıdır.");

$cl_units->add_unit("Koçbaşı","unit_ram");
$cl_units->set_woodprice("300");
$cl_units->set_stoneprice("200");
$cl_units->set_ironprice("200");
$cl_units->set_bhprice("5");
$cl_units->set_time("1250");
$cl_units->set_att("100","1.045");
$cl_units->set_def("100","1.045");
$cl_units->set_defcav("200","1.045");
$cl_units->set_defarcher("20","1.045");
$cl_units->set_speed("1200");
$cl_units->set_booty("0");
$cl_units->set_needed(array("garage"=>"1"));
$cl_units->set_recruit_in("garage");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("C");
$cl_units->set_attType("off");
$cl_units->set_description("Koçbaşı düşman duvarlarını yıkmak için kullanılır. Ağır olduğu için yavaş hareket eder.");

$cl_units->add_unit("Mancınık","unit_catapult");
$cl_units->set_woodprice("320");
$cl_units->set_stoneprice("400");
$cl_units->set_ironprice("100");
$cl_units->set_bhprice("8");
$cl_units->set_time("1250");
$cl_units->set_att("500","1.045");
$cl_units->set_def("400","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("1440");
$cl_units->set_booty("0");
$cl_units->set_needed(array("garage"=>"2","smith"=>"12"));
$cl_units->set_recruit_in("garage");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("C");
$cl_units->set_attType("undefined");
$cl_units->set_description("Mancınık, ağır taşları düşmanların üzerine fırlatarak binaları bombalar. Tek başına savunma yapamadığı için mutlaka bir refakat birliğine ihtiyaç duyar.");

$cl_units->add_unit("Şövalye","unit_knight");
$cl_units->set_woodprice("20");
$cl_units->set_stoneprice("20");
$cl_units->set_ironprice("40");
$cl_units->set_bhprice("10");
$cl_units->set_time("34424");
$cl_units->set_att("150","1.045");
$cl_units->set_def("250","1.045");
$cl_units->set_defcav("400","1.045");
$cl_units->set_defarcher("150","1.045");
$cl_units->set_speed("400");
$cl_units->set_booty("100");
$cl_units->set_needed(array());
$cl_units->set_recruit_in("statue");
$cl_units->set_specials(array("no_investigate"));
$cl_units->set_group("cav");
$cl_units->set_col("D");
$cl_units->set_attType("undefined");
$cl_units->set_description("Şövalye köyünüzü ve müttefiklerinizi düşman saldırılarına karşı korur. Her oyuncunun yalnızca bir şövalyesi olabilir.");

$cl_units->add_unit("Misyoner","unit_snob");
if($config['ag_style'] == 2){
  $cl_units->set_woodprice("40000");
  $cl_units->set_stoneprice("50000");
  $cl_units->set_ironprice("50000");
}else{
  $cl_units->set_woodprice("28000");
  $cl_units->set_stoneprice("30000");
  $cl_units->set_ironprice("25000");
}
$cl_units->set_bhprice("100");
$cl_units->set_time("12500");
$cl_units->set_att("100","1.045");
$cl_units->set_def("300","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("1800");
$cl_units->set_booty("0");
$cl_units->set_needed(array("main"=>"20","smith"=>"20","market"=>"10"));
$cl_units->set_recruit_in("snob");
$cl_units->set_specials(array("no_investigate"));
$cl_units->set_group("foot");
$cl_units->set_col("D");
$cl_units->set_attType("undefined");
$cl_units->set_description("Misyoner, hedef köyün sadakatini düşürür ve yeterli sayıda başarılı saldırıdan sonra köyü fetheder.");
?>
